"""scripts/build_site_pages.py — build the two narrative site pages:

  docs/results/index.html   — Total results & recommendations (the executive capstone)
  docs/process/index.html   — How the MMM competition works (the methodology)

Reuses the shared CSS + table helper and pulls the leaderboard numbers from the per-seed snapshots
so the results page stays in sync with the data. CONTRACT: reporting only.
"""
from __future__ import annotations

import pathlib
import sys

import numpy as np

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import make_report as mr      # noqa: E402  CSS + _tbl
import robustness as rb       # noqa: E402  load_runs + aggregate + _row
from draftzone_mmm.model import REPO  # noqa: E402

DOCS = REPO / "docs"


def _page(title, sub, body):
    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title}</title><style>{mr.CSS}</style></head><body>
<header class="hero"><div class="wrap">
<div class="kicker">A Skeptic's Guide to Marketing Mix Modeling</div>
<h1>{title}</h1>
<p class="sub">{sub}</p>
</div></header>
<main class="wrap">{body}</main>
<footer class="wrap">Generated by <code>scripts/build_site_pages.py</code> ·
<a href="../index.html">dashboard</a> · <a href="../robustness/index.html">multi-seed leaderboard</a> ·
<a href="../conditional/index.html">which engine when</a> ·
<a href="../engines/index.html">single-seed deep dive</a> · <a href="../runs/index.html">run tracker</a></footer>
</body></html>"""


def _leaderboard_table():
    runs = rb.load_runs()
    eng = rb.aggregate(runs)
    nat = {k: v for k, v in eng.items() if v["world"] == "national"}
    rows = sorted((rb._row(k, v, len(runs)) for k, v in nat.items()), key=lambda r: r["avg_rank"])
    out = []
    for r in rows:
        rank = f"{r['avg_rank']:.1f}" if np.isfinite(r["avg_rank"]) else "—"
        out.append([r["label"], str(r["n"]), rank, str(r["wins"]),
                    f"{r['med_mae']:.0f}", f"±{r['mae_std']:.0f}", f"{r['mean_bias']:+.0f}%",
                    f"{r['diverged']}" if r["diverged"] else "—"])
    tbl = mr._tbl(["engine", "runs", "avg rank ↓", "wins", "median MAE", "spread", "mean bias",
                   "diverged"], out)
    return tbl, len(runs)


def build_results():
    tbl, n = _leaderboard_table()
    body = f"""
<section><div class="card">
<h2>The bottom line</h2>
<p>We ran a controlled competition: a synthetic world where every channel's true effect is sealed in
an answer key, and a dozen MMM approaches — naive regression, our Bayesian model, Google Meridian,
Meta Robyn (the real R package), a spend-ladder experiment — all graded against that truth across
many independent datasets. Three results matter more than any single number:</p>
<ol>
<li><b>There is no single "best" MMM.</b> Across {n} datasets the top engines (Meridian, our PyMC,
Robyn-style) are <b>tied within the run-to-run noise</b>; the apparent winner changes with the data.
Anyone who shows you one leaderboard and declares a champion is fooling themselves. But the choice is
not arbitrary either — <b>different engines suit different data</b> (see the
<a href="../conditional/index.html">which-engine-when guide</a>): the spend ladder earns its keep when
channels are saturated, while a flexible engine like Robyn does relatively better with headroom.</li>
<li><b>An observational MMM is only as trustworthy as its confound control.</b> Spend chases demand
(here, correlation ~0.6 with season), so without strong seasonality controls — and ideally a
randomized experiment — attribution is biased in a direction you cannot know from the fit.</li>
<li><b>Goodness-of-fit lies.</b> Engines hit R² 0.85–0.99 while mis-crediting channels by ±50–120%.
Fit quality tells you almost nothing about decomposition quality.</li>
</ol>
</div></section>

<section><div class="card">
<h2>Multi-seed leaderboard ({n} datasets)</h2>
{tbl}
<p class="small">Ranked by average rank across datasets (lower is better). "spread" is the across-seed
std of MAE — the stability that actually matters. The full, always-current version with geo engines
and sampling diagnostics is the <a href="../robustness/index.html">multi-seed leaderboard</a>.</p>
</div></section>

<section><div class="card">
<h2>What we learned, by approach</h2>
<ul>
<li><b>Regularisation is not optional.</b> The two engines that <i>diverged</i> on real datasets —
frequentist NLS and the raw spend-ladder curve fit — were the two with <i>unregularised least
squares</i>. Adding a prior/ridge fixed both (NLS: a seed hit MAE 47,000 → ~130; ladder: max
360 → 98). In thin-data, many-parameter MMM, priors are what keep the fit on the road.</li>
<li><b>Control seasonality, idiomatically.</b> Meridian's AKS knots and a Fourier basis are two roads
to the same end; without either, the spend↔season confound roughly doubles attribution.</li>
<li><b>Geo data buys precision, not immunity.</b> A geo-level model is sharper, but against an
<i>unobserved</i> geo confounder it becomes confidently wrong (+120% bias, 0/6 intervals covering
truth). Even a near-perfect demand-proxy control only claws back about half. More observational data
is not a substitute for randomization.</li>
<li><b>Experiments are the anchor — but feed them correctly.</b> Bolting a single lift number onto a
model as a scalar prior usually <i>hurt</i> (over-credited by 100%+). Curve-aware calibration (feed
the lift at its measured exposure, or trace the curve with a spend ladder) is the right way — and it
is still capped by the experiment's own accuracy.</li>
<li><b>The spend ladder cracks saturated channels — at a real cost.</b> Multiple bracketed test cells
measure the response curve that a single test can only assume; it is the one method that right-sizes
saturated channels, but it costs a quarter of calendar time, scarce geo inventory, and a real media
tax. See the <a href="../ladder/index.html">spend-ladder analysis</a>.</li>
</ul>
</div></section>

<section><div class="card">
<h2>Recommendations</h2>
<ol>
<li><b>Default to a regularised Bayesian MMM</b> and report uncertainty on every number. Point
estimates without intervals are how teams talk themselves into spurious precision.</li>
<li><b>Always control seasonality and known demand drivers.</b> If you cannot, assume your media is
over-credited.</li>
<li><b>Measure your confound.</b> If spend correlates strongly with demand and you have no experiment,
treat the decomposition as a hypothesis, not an answer.</li>
<li><b>Triangulate with randomized geo experiments.</b> A geo lift test / spend ladder is the only
confound-immune evidence. Feed it curve-aware, not as a naive scalar prior.</li>
<li><b>Decide on MARGINAL ROI under uncertainty,</b> not average ROI — and split channels into
<i>confident</i> moves (act now) vs <i>test-first</i> (run an experiment before reallocating).</li>
<li><b>Check robustness.</b> Refit on data subsets / time folds; if the ranking of channels flips,
your "answer" is noise. One leaderboard is never enough.</li>
</ol>
</div></section>

<section><div class="card">
<h2>Run it on your data</h2>
<p>The recommendations above are packaged. <code>draftzone_mmm.run.run_mmm</code> fits the
findings-optimised configuration — regularised priors, seasonality control, uncertainty everywhere,
a confound diagnostic, marginal ROI, and a confident-vs-test-first recommendation:</p>
<pre>from draftzone_mmm.run import run_mmm

res = run_mmm(
    df,                                  # one row per week
    kpi="conversions",                   # your outcome column
    channels=["tv", "search", "social"],
    spend_suffix="_spend",               # -> tv_spend, search_spend, ...
    exposure_suffix="_impressions",      # optional; defaults to spend
    controls=["price", "promo"],         # optional observed confounders
    date="week",
)

print(res.summary())                     # contributions+CIs, confound, marginal ROI, verdicts
res.contributions    # per-channel avg contribution with 89% credible intervals
res.roi              # average AND marginal ROI per channel
res.recommend()      # scale-up / cut (confident) vs test-first (uncertain)</pre>
<p class="small">It is a single well-configured engine, deliberately conservative: when the confound
is high and the posterior is wide it will tell you to <b>test first</b> rather than hand you a false
answer. For a head-to-head of engines on your data, use the competition harness.</p>
</div></section>
"""
    out = DOCS / "results" / "index.html"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(_page("Results & recommendations",
                         f"What {n} graded datasets say about trusting MMM — and what to do about it.",
                         body), encoding="utf-8")
    print(f"Wrote {out}")


def build_process():
    body = """
<section><div class="card">
<h2>Why a competition</h2>
<p>On real data you never learn whether your MMM was right — there is no answer key. So we built a
synthetic world where there <i>is</i> one. Every channel's true carryover, saturation, and effect are
generated from known parameters and <b>sealed</b> in <code>data_sealed/ground_truth.json</code>. A
hard rule, enforced by a test, keeps the modeling pipeline from ever reading it; only the grader may.
Every engine then competes to recover the truth it cannot see.</p>
</div></section>

<section><div class="card">
<h2>The synthetic world (the data-generating process)</h2>
<ul>
<li><b>Channels with distinct physics.</b> Six media channels, each with its own carryover (geometric
adstock θ from 0.10 to 0.75) and diminishing returns (Hill saturation), spanning saturated
(paid_social, paid_search, tv) and headroom (influencer, dooh) channels.</li>
<li><b>The confound.</b> Spend is paced to demand, so total spend correlates ~0.6 with seasonality —
the central reason naive attribution is biased.</li>
<li><b>Controls + noise.</b> Promotions, price, competitor pressure, holidays, plus realistic noise.</li>
<li><b>Experiments.</b> A rotating per-channel geo lift test, and a multi-cell <b>spend ladder</b>
that brackets each channel's operating point to measure (not assume) its response curve.</li>
<li><b>A hardened geo panel.</b> A 50-geo world with a latent, unobserved demand confounder (affluent
DMAs spend more <i>and</i> convert more) — to test whether geo-level models survive a real confound.</li>
</ul>
</div></section>

<section><div class="card">
<h2>The competitors</h2>
<ul>
<li><b>Naive OLS</b> — linear regression on spend. The blunt baseline.</li>
<li><b>Frequentist NLS</b> — non-linear least squares with adstock+Hill (now ridge-regularised).</li>
<li><b>DraftZone PyMC</b> — our regularised Bayesian MMM, observational and (optionally)
experiment-anchored.</li>
<li><b>Google Meridian</b> — the real package, with Fourier vs its native AKS seasonality, and on the
multi-geo panel with a spectrum of demand-proxy controls.</li>
<li><b>Meta Robyn</b> — the real R package (ridge + Nevergrad + Prophet + DECOMP.RSSD), plain and
experiment-calibrated, plus a faithful Python reimplementation.</li>
<li><b>Spend ladder</b> — a pure-experiment readout that fits the response curve from bracketed test
cells.</li>
</ul>
</div></section>

<section><div class="card">
<h2>How we score</h2>
<ul>
<li><b>MAE per channel</b> — mean absolute error of recovered avg weekly contribution vs sealed truth.
The headline metric.</li>
<li><b>Media bias</b> — total recovered media vs truth (over/under-crediting).</li>
<li><b>Interval coverage</b> — for Bayesian engines, does the 89% credible interval contain the truth?</li>
<li><b>Sampling quality (ESS / R-hat)</b> — a recovery you couldn't sample isn't a recovery.</li>
<li><b>Divergence guard</b> — an engine whose fit blew up is flagged and kept out of the chart.</li>
</ul>
<p>Geo engines are graded against the geo world's <i>own</i> answer key (it differs from national by
a small aggregation gap plus the confounder), never the national one.</p>
</div></section>

<section><div class="card">
<h2>The robustness protocol — why one dataset is never enough</h2>
<p>A single graded dataset answers "who won <i>this</i> world?"; that ranking is unstable. So we
regenerate the entire world under many seeds and aggregate by <b>average rank, win-rate, and MAE
spread</b>. Each seed is independent — new data, new experiments, new sealed truth — so nothing is
reused; every engine is recomputed every run. The honest output is a distribution with overlap, not
a podium. Tellingly, even the <i>robustness</i> ranking shifted between 6 and 10 seeds: at 6 seeds one
engine looked like a clear champion; at 10 its lead was inside the noise. Stability claims need
samples too.</p>
<p class="small">See the <a href="../robustness/index.html">multi-seed leaderboard</a> for the live
ranking, the <a href="../engines/index.html">single-seed deep dive</a> for one world in detail, and the
<a href="../results/index.html">results &amp; recommendations</a> for what it all means.</p>
</div></section>
"""
    out = DOCS / "process" / "index.html"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(_page("How the MMM competition works",
                         "Sealed-truth grading, a dozen engines, and a multi-seed protocol.", body),
                   encoding="utf-8")
    print(f"Wrote {out}")


def main():
    build_results()
    build_process()


if __name__ == "__main__":
    main()
